{"uuid": "159375f2-7377-49fc-9743-678af98915d8", "children": ["2c63c5c0-13bb-4e79-9695-d745a52925ad"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"c:\\python3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\python3\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\python3\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\1\\Downloads\\Book_store_OOP_example\\Book_store_POM_example\\conftest.py\", line 17, in browser\n  File \"c:\\python3\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"c:\\python3\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1637689376208, "stop": 1637689376213}], "start": 1637689376208, "stop": 1637689376234}